<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SAVI.Tools</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SAVI.Application\SAVI.Application.csproj" />
    <ProjectReference Include="..\SAVI.Core\SAVI.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
